---

# Stretch Tenant on Application Playbook
- name: Creating a Stretch Tenant on Multisite
  hosts: mso1
  connection: local
  gather_facts: no

  vars_files:
  - external_vars.yml

  vars:
    status: present

  tasks:
  - name: "Add a new tenant"
    delegate_to: localhost
    mso_tenant:
     host: "{{ host }}"
     username: "{{ user }}"
     password: "{{ pass }}"
     tenant: "{{ tenant }}"
     display_name: "Ansible Tenant T01"
     description: "Tenant configured by Ansible"
     users: "{{ user }}"



     sites:
       - "{{ site1 }}"
       - "{{ site2 }}"
     state: "{{ status }}"
     use_ssl: yes
     validate_certs: no
     use_proxy: no


#
# Usage:  sudo ansible-playbook tenant.yml -i hosts  -vvv
#
#  docs.ansible.com is essential to make sure you got the modules right
# variables are defined in external_varsATX.yml

